server :
  port : 8080
  servlet.context-path : /springboot

spring:
  profiles.active: @profileActive@

#  mail:
#    host: smtp.qq.com
#    protocol: smtp
#    default-encoding: UTF-8
#    password: fzvarxpndockbaeg
#    username: 1102211390@qq.com
#    port: 587
#    properties:
#      mail:
#        stmp.socketFactory.class: javax.net.ssl.SSLSocketFactory
#        debug: true

  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true


  resources.static-locations: classpath:/templates/,classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/sm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    multipart.max-file-size: 500MB
    multipart.max-request-size: 500MB

  redis:
    port: 6379
    host: localhost
    database: 0



mybatis :
  mapper-locations: classpath:/com/hz/mapper/*.xml
  type-aliases-package: com.hz.demo.entity

logging:
  level:
    root: info
    com.hz.dao: debug

    eureka.client.healthcheck.enabled: false

