#使用的端口号
server :
  port : 8080
#项目的名称
  server.servlet.context-path : /springboot

#使用的配置文件
spring:
  profiles.active: dev

  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: fzvarxpndockbaeg
    username: 1510161612@qq.com
    port: 587
    properties:
      mail:
        stmp.socketFactory.class: javax.net.ssl.SSLSocketFactory
        debug: true

  #去哪个目录下找什么模板
  #spring.thymeleaf.prefix=classpath:/templates/
  #spring.thymeleaf.suffix=.html
  #spring.thymeleaf.encoding=UTF-8
  #spring.thymeleaf.servlet.content-type=text/html
  #让模板既是模板又是静态资源

  resources.static-locations: classpath:/templates/,classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/sm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    multipart.max-file-size: 500MB
    multipart.max-request-size: 500MB

  redis:
    port: 6379
    host: localhost
    database: 0

mybatis :
  mapper-locations: classpath:/com/hz/mapper/*.xml
  type-aliases-package: com.hz.entity

logging:
  level:
    root: info
    com.hz.dao: debug


spring.mail:
  host: smtp.qq.com
  protocol: smtp
  default-encoding: UTF-8
  password: kuwvhzyxkknujigi
  username: 1102211390@qq.com
  port: 465
  properties.mail.stmp.socketFactory.class: javax.net.ssl.SSLSocketFactory
  properties.mail.debug: true
  properties.mail.mail.host: smtp.qq.com
  properties.mail.smtp.protocol: smtp
  properties.mail.smtp.auth: true
  properties.mail.smtp.port: 465



eureka.client.healthcheck.enabled: true
# rabbitmq 服务所在ip
spring.rabbitmq.host: 127.0.0.1
# rabbitmq 端口
spring.rabbitmq.port: 5672
# rabbitmq 账号
spring.rabbitmq.username: guest
# rabbitmq 密码
spring.rabbitmq.password: guest
# 消息总线相关
management.endpoints.web.exposure.include: bus-refresh

#设置jsp页面 使用以下三个配置时需要放开jstl相关的maven依赖
#spring.mvc.view.prefix= /
#spring.mvc.view.suffix=.jsp
#开启jsp页面的热部署
#server.servlet.jsp.init-parameters.development =true