server :
  port : 8085
  #servlet.context-path : /springbootbook

spring:
  application:
    name: springbootbook
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/sm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  security:
    user:
      password: ${REGISTRY_SERVER_PASSWORD:password}
      name: user

mybatis :
  mapper-locations: classpath:/com/hz/mapper/*.xml
  type-aliases-package: com.hz.demo.entity

#  data:
#    mongodb:
#      database: admin
#      host: 127.0.0.1
#      password:
#      port: 27017
#      username:

eureka:
#  instance:
#    hostname: localhost
  client:
    serviceUrl:
      #defaultZone: http://127.0.0.1:6890/eureka/
      defaultZone: http://user:password@localhost:6890/eureka
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/

    healthcheck:
      enabled: true

    #registerWithEureka: false
    #fetchRegistry: false
  instance:
    instance-id: springbootbook-8085
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
management:
  endpoints:
    web:
      exposure:
          include=*,hystrix:
            stream:

info:
  app.name: eureka
  company:
    name: hz
  build:
    artifactId: @project.artifactId@
    version: @project.version@

feign:
  hystrix:
    enabled: true