server:
  port: 6890
eureka:
  #  instance:
  #    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@127.0.0.1:${server.port}/eureka/
      #defaultZone: http://localhost:6890/eureka/
management:
  health:
    redis:
      enabled: false
spring:
  resources.static-locations: classpath:/templates/,classpath:/static/
  security:
    user:
      password: ${REGISTRY_SERVER_PASSWORD:password}
      name: user
#  datasource:
#      url: jdbc:mysql://localhost:3306/sm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      username: root
#      password: root
#      type: com.alibaba.druid.pool.DruidDataSource

