#???????
server :
  port : 8084
  #?????????
  servlet.context-path : /springbootemail

#???????????
spring:
  application:
    name: springbootEmail
  mail:
    host: smtp.qq.com
    protocol: smtp
    default-encoding: UTF-8
    password: kuwvhzyxkknujigi
    username: 1102211390@qq.com
    port: 587
    properties:
      mail:
        stmp.socketFactory.class: javax.net.ssl.SSLSocketFactory
        debug: true

  #???????????????
  #spring.thymeleaf.prefix=classpath:/templates/
  #spring.thymeleaf.suffix=.html
  #spring.thymeleaf.encoding=UTF-8
  #spring.thymeleaf.servlet.content-type=text/html
  #????????????????????

  resources.static-locations: classpath:/templates/,classpath:/static/
  datasource:
    url: jdbc:mysql://localhost:3306/sm?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  servlet:
    multipart.max-file-size: 500MB
    multipart.max-request-size: 500MB

  redis:
    port: 6379
    host: localhost
    database: 0

  #rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
  listener:
    simple:
      concurrency: 5
      ## manual:??? ack??????
      acknowledge-mode: manual
      max-concurrency: 10
      prefetch: 1


logging:
  level:
    root: info
    com.hz.dao: debug

#management.endpoints.web.exposure.include: bus-refresh

## springboot????rabbitmq?????????



#????jsp??? ??????????????????????jstl????maven????
#spring.mvc.view.prefix= /
#spring.mvc.view.suffix=.jsp
#????jsp?????????
#server.servlet.jsp.init-parameters.development =true

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6890/eureka/
    healthcheck:
      enabled: true

info:
  app.name: eureka
  company:
    name: hz
  build:
    artifactId: @project.artifactId@
    version: @project.version@